<a href="https://colab.research.google.com/github/tasnim-shamsuddin/RNN/blob/main/embedding.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [42]:
from tensorflow.keras.preprocessing.text import one_hot


In [43]:
sent=[
    'I am a data scientist',
    'I am creative at my work',
    'I live in Bahrain',
    'Someday i want to open a kitchen items shop'
]

In [44]:
sent

['I am a data scientist',
 'I am creative at my work',
 'I live in Bahrain',
 'Someday i want to open a kitchen items shop']

In [45]:
##defining vocabulary size
voc_size=10000


In [46]:
##one hot representation
one_hot_rep=[one_hot(words,voc_size) for words in sent]
print(one_hot_rep)


[[6114, 3560, 2754, 306, 3962], [6114, 3560, 8209, 7070, 9392, 1317], [6114, 6074, 8830, 5248], [4455, 6114, 8636, 5838, 2035, 2754, 5136, 2978, 2048]]


In [47]:
##word embeding representation

from tensorflow.keras.layers import Embedding
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential


In [48]:
import numpy as np

In [49]:
sent_length=8
embedded_docs=pad_sequences(one_hot_rep,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0 6114 3560 2754  306 3962]
 [   0    0 6114 3560 8209 7070 9392 1317]
 [   0    0    0    0 6114 6074 8830 5248]
 [6114 8636 5838 2035 2754 5136 2978 2048]]


In [50]:
##Feature representation
dim=10


In [51]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [52]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_6 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [53]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 732ms/step


array([[[ 0.01081635,  0.04178711,  0.04570875,  0.00019251,
         -0.00896619,  0.04752493,  0.01867172,  0.00885166,
         -0.00395541,  0.00119239],
        [ 0.01081635,  0.04178711,  0.04570875,  0.00019251,
         -0.00896619,  0.04752493,  0.01867172,  0.00885166,
         -0.00395541,  0.00119239],
        [ 0.01081635,  0.04178711,  0.04570875,  0.00019251,
         -0.00896619,  0.04752493,  0.01867172,  0.00885166,
         -0.00395541,  0.00119239],
        [-0.00379895, -0.01895308,  0.04366544, -0.02856044,
          0.01025198,  0.02267486, -0.00078187,  0.04245826,
          0.01660867,  0.00675734],
        [-0.03450572, -0.0218237 ,  0.01525157, -0.0053306 ,
         -0.03415263, -0.01888666,  0.02404514,  0.0403329 ,
          0.04415132,  0.01558951],
        [ 0.02021178, -0.02022634, -0.0089005 ,  0.02759452,
         -0.04034638, -0.01334162,  0.02820099, -0.00784772,
         -0.00722701,  0.02634997],
        [-0.00242611, -0.02668713,  0.03006656,  0.0